"""add youtube_refresh_token and youtube_channel_name to users

Revision ID: 214434ea743b
Revises: 24d955d97ff3
Create Date: 2025-11-26 15:25:49.334775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214434ea743b'
down_revision: Union[str, None] = '24d955d97ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('youtube_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('youtube_channel_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'youtube_channel_name')
    op.drop_column('users', 'youtube_refresh_token')
    # ### end Alembic commands ###
