"""Add runs table

Revision ID: ba0d48d168b2
Revises: 5828cfcf554d
Create Date: 2025-11-19 15:06:35.797347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0d48d168b2'
down_revision: Union[str, None] = '5828cfcf554d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('GENERAL', 'STORY', 'AD', name='runmode'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('num_cuts', sa.Integer(), nullable=True),
    sa.Column('num_characters', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('IDLE', 'PLOT_GENERATION', 'PLOT_REVIEW', 'ASSET_GENERATION', 'LAYOUT_REVIEW', 'RENDERING', 'QA', 'COMPLETED', 'FAILED', name='runstate'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('credits_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_run_id'), 'runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_runs_user_id'), 'runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_user_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_run_id'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
